name: 'Deploy to AWS S3 with JS Action'
description: 'Deploy a static website via AWS S3'
inputs:
  bucket:
    description: 'S3 Bucket name'
    required: true
  bucket-region:
    description: 'S3 Bucket region'
    required: false
    default: 'eu-central-1'
  dist-folder:
    description: 'The folder contains the deployable files'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
